GET http://localhost:5000/api/islands/b674ceda0cee776832b17dbfd56f9666046ff112d7fb33ae6931d255229ad0e4

###

GET http://localhost:5000/api/islands/fundraisers

###

GET http://localhost:5000/api/islands

###

GET http://privateislands.fund:5000/api/islands/fundraisers

###

GET http://localhost:5000/api/islands/integrate/sub/dero1qyczef08vznftr9w4dg6f4ejracm4wuemq8hyczqudxn8y8h8w6evqgdqnncr/apollo0

###

GET http://127.0.0.1:5000/api/contracts