GET http://localhost:5000/api/islands/cf530bd98d200171a94bcd6ef1e3ad6348bfa3e6691196e64e93e7953b64a2e4

###

GET http://localhost:5000/api/islands/fundraisers

###

GET http://localhost:5000/api/islands

###

GET http://privateislands.fund:5000/api/islands/fundraisers

###

GET http://localhost:5000/api/islands/integrate/sub/dero1qyczef08vznftr9w4dg6f4ejracm4wuemq8hyczqudxn8y8h8w6evqgdqnncr/apollo0